@echo off
:: Android Studio One-Click Launch Script for TauriTavern
:: Generated by Antigravity (Updated with verified paths)

set "GRADLE_USER_HOME=D:\software_cache\.gradle"
set "ANDROID_USER_HOME=D:\software_cache\.android"
set "CARGO_HOME=D:\software_cache\.cargo"
set "RUSTUP_HOME=E:\LibSoftware\Rust\rustup"
set "JAVA_HOME=E:\Yuqiu\software\android_studio\jbr"
set "ANDROID_NDK_HOME=E:\LibSoftware\android_sdk\ndk\29.0.14206865"

set "STUDIO_PATH=E:\Yuqiu\software\android_studio\bin\studio64.exe"

if not exist "%STUDIO_PATH%" (
    echo ======================================================
    echo [ERROR] Android Studio was not found at:
    echo %STUDIO_PATH%
    echo.
    echo Please edit this .bat file and set the correct 
    echo STUDIO_PATH at the top.
    echo ======================================================
    pause
    exit /b 1
)

echo [1/2] Setting environment variables...
echo GRADLE_USER_HOME: %GRADLE_USER_HOME%
echo ANDROID_USER_HOME: %ANDROID_USER_HOME%
echo CARGO_HOME: %CARGO_HOME%
echo JAVA_HOME: %JAVA_HOME%

echo [2/2] Launching Android Studio...
start "" "%STUDIO_PATH%" "D:\data\TauriTavern\src-tauri\gen\android"

echo.
echo ======================================================
echo Project directory: D:\data\TauriTavern\src-tauri\gen\android
echo Android Studio is opening. Once it's ready:
echo.
echo 1. Click "Sync Project with Gradle Files" (Elephant icon)
echo 2. Important: Use the "Build" menu -> "Select Build Variant"
echo    and choose "universalDebug".
echo 3. Build -> Make Project.
echo ======================================================
echo.
timeout /t 5
